sudo: required
language: node_js
node_js:
  - '5'
  - '4'
  - '0.12'
before_install:
  - sudo apt-get update
  - sudo apt-get install oracle-java8-installer
  - sudo update-java-alternatives -s java-8-oracle
