sudo: required
language: node_js
env:
  - NODE_VERSION=0.12
  - NODE_VERSION=4
  - NODE_VERSION=5
jdk:
  - oraclejdk8
before_install:
  - sudo apt-get update
  - sudo apt-get install oracle-java8-installer
  - sudo update-java-alternatives -s java-8-oracle
  - nvm install "$NODE_VERSION"
  - node --version
  - npm --version
  - java -version
install:
  - npm install -g grunt-cli
  - grunt --version
  - npm install
script:
  - npm test
matrix:
  fast_finish: true
